import { shell } from "./render.ts";

export function pitch(): string {
  return shell("pitch", `
    <section class="pitch-heading"><p class="kicker">Fork · for solo builders & small to medium teams</p><h1>Stop guessing. Try the alternatives.</h1><p class="lede">No dedicated product team? When Cursor reaches a product choice, Fork gives you working alternatives, real Grok Bot investigations and a decision the agent can build from.</p></section>
    <div class="pitch-grid">
      <section class="pitch-panel"><p class="kicker">01 · Start in Cursor</p><h2>A question, not a guess.</h2><pre><code>/fork How should people
find their next show?</code></pre><p>A repo command guides Cursor to build distinct alternatives for your question.</p><button class="ghost" data-copy-start>Copy Cursor prompt</button><p class="copy-start-status" role="status"></p></section>
      <section class="pitch-panel"><p class="kicker">02 · Explore in Fork</p><h2>See it working.</h2><div class="pitch-options"><a href="/v/browse" data-link><strong>Browse</strong><span>Visible filters</span></a><a href="/v/ask" data-link><strong>Ask</strong><span>Talk to Grok</span></a><a href="/v/guide" data-link><strong>Guide</strong><span>One step at a time</span></a></div><p>Shared data. Different product assumptions. This example uses tickadoo shows.</p></section>
      <section class="pitch-panel"><p class="kicker">03 · Grok Bot investigates</p><h2>Proof, not a prediction.</h2><a class="pitch-capture" href="/walkthrough" data-link><img src="/walkthroughs/group-organiser-guide/final.png" width="1024" height="525" alt="Actual Grok Bot capture of the working Guide selection" /><span>Actual Grok Bot capture</span></a><ul class="pitch-findings"><li><strong>Browse</strong><span>£80 → £50 budget: a different show.</span></li><li><strong>Speedrunner · Ask</strong><span>Mobile run found extra scrolling. We moved the next step up.</span></li><li><strong>Group Organiser · Guide</strong><span>Age + runtime + budget twist: both choices fit.</span></li></ul><a class="primary pitch-next" href="/walkthrough" data-link>Next: show Grok Bot proof →</a></section>
    </div>
    <section class="pitch-finish"><div><p class="kicker">04 · You decide. Cursor continues.</p><h2>Choose a direction. Keep the context.</h2><p>Your reason and evidence become a copyable Cursor handoff. An operator can record the decision and explicitly adopt it in the repo.</p></div><a class="primary" href="/compare#decision" data-link>See the decision & handoff →</a></section>
    <div class="pitch-bottom"><p><strong>Any product question.</strong> Configure alternatives, missions and checks for checkout, onboarding, search or pricing.</p><div class="row"><a class="ghost" href="/v/ask" data-link>Try working demo →</a><a class="ghost" href="https://github.com/Mark-Prethero/get-fork" target="_blank" rel="noopener noreferrer">Inspect GitHub code ↗</a></div></div>
    <p class="demo-next-key">Follow the lime buttons to present the story.</p><p class="pitch-note">Real Bot reports are already captured. Mission transfer to Grok Bot is manual today. Agent walkthroughs help investigation; they are not real-user research. Show prices and suitability are demo scenarios.</p>
  `);
}
