/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.worker.jsonc --include-runtime=false --strict-vars=false --env-interface=WorkerBindings src/worker-bindings.d.ts` (hash: 76f73f93867af654342f09c403528c26)
interface __BaseEnv_WorkerBindings {
	EVIDENCE: KVNamespace;
	DB: D1Database;
	ASSETS: Fetcher;
	GROK_MODEL: string;
	PUBLIC_BASE_URL: string;
	ASK_CALL_BUDGET: string;
	XAI_API_KEY: string;
	ADMIN_KEY: string;
	BOT_INGEST_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GROK_MODEL" | "PUBLIC_BASE_URL" | "ASK_CALL_BUDGET" | "XAI_API_KEY" | "ADMIN_KEY" | "BOT_INGEST_KEY">> {}
}
